### ISSUE TITLE
No content of articles is shown without teaser content

### ISSUE THREAD

**Issue by jscholtysik** [webrealisierung-ch/onepage-bundle#10]
I have the following configuration:

- Contao 4.4.12
- wr/onepage-bundle 1.0.4

I did a complete new Contao installation with 4.4.12, updated all components with the Contao manager and installed the wr/onepage-bundle 1.0.4 .
Then I created all necessary Contao stuff (onepage module, page layout, theme) and a new site structure with 1 page and under this page 3 articles.
Then I included the onepage module in the page layout.

The frontend showed the one page navigation of the module, but no content of the articles. so I tried different things to get the content of the articles as well, but with no success. Then I tried to fill the teaser textfields of the articles and voila, all content did show up.
For clarification I removed all teaser text of all articles again, but all content is still visible, so this seems to be a problem with the teaser text fields.

Is this misbehaviour reproducible for you?

**Comment by danielsteuri** [comment]
Thank you for your feedback. We will check this soon as possible.

**Comment by danielsteuri** [comment]
@jscholtysik We did some further tests with different new contao(4.4.12) instances and different hosting platforms. Unfortunately we could not reproduce this misbehavior. Are there any errors in the log files?

**Comment by jscholtysik** [comment]
No, unfortunately there are no errors in the log files. I only saw in the source code that the content of the articles was not loaded. After inserting the teaser text I also saw the content of the articles.

**Comment by danielsteuri** [comment]
We could not reproduce this misbehavior. Tested on different platform and Contao Versions( 4.4.12 <).
