### ISSUE TITLE
Reference page gets ".html" suffix by default

### ISSUE THREAD

**Issue by Seefahrer** [webrealisierung-ch/onepage-bundle#2]
In case someone is running Contao 4.4.x without page suffix as per /app/config/config.yml, use of OnePage navigation will result in an 404 error, as the .html suffix is appended to the reference page by default. 
Line 12 of file /vendor/wr/onepage-bundle/src/Resources/contao/modules/ModuleWrOnepage.php needs to be changed: 

`$this->Template->uri = $rootPageId->alias.$_ENV['url_suffix'];`

`<?php

class ModuleWrOnepage extends \Module {

    protected $strTemplate = 'mod_wr_onepage';
    protected function compile()
    {
        global $objPage;
        if($this->rootPage){
            $Articles=\Contao\ArticleModel::findByPid($this->rootPage);
            $rootPageId=\Contao\PageModel::findById($this->rootPage);
            $this->Template->uri = $rootPageId->alias.$_ENV['url_suffix'];
        } else{
            $Articles=\Contao\ArticleModel::findByPid($objPage->id);
            $this->Template->uri = $_ENV['REQUEST_URI'];
        }
        $arrArticle = array();
        foreach($Articles as $article){
            if(strlen($article->in_onepage && $article->published)){
                array_push($arrArticle,
                    array(
                        'title'=>$article->title,
                        'alias'=>$article->alias
                    )
                );
            }
        }
        $this->Template->arrArticle = $arrArticle;
    }
}`

**Comment by danielsteuri** [comment]
The module class is updated to the contao url_generator service and the getFrondendUrl method. 
 
``` php
//$this->Template->uri = $rootPageId->alias.".html";
$this->Template->uri = $rootPageId->getFrontendUrl('');
        
// $this->Template->uri = $_ENV['REQUEST_URI'];
$urlGenerator=\Contao\System::getContainer()->get('contao.routing.url_generator');
$this->Template->uri = $url=$urlGenerator->generate($objPage->alias);
```

Other url suffix given in the config.yml should work now.

Let us know if this solves your 404 error.

Thank you!

**Comment by Seefahrer** [comment]
Thx, 404 is perfectly fixed after a.m. amendment!
