### ISSUE TITLE
onpage.js als min.ls

### ISSUE THREAD

**Issue by bitsmakerde** [webrealisierung-ch/onepage-bundle#5]
Hallo,

mir ist aufgefallen, dass die Onepage.js nicht als min.js zur Verfügung steht. ist es möglich diese im Packet als Standard zu laden?

Vielen Dank

**Comment by danielsteuri** [comment]
Guten Tag,

Ist korrekt. Werde ich mit dem Release im Verlauf der nächsten Woche beheben.

Lieber Gruss

**Comment by danielsteuri** [comment]
Closed in ```0a70e9b```
